#!/bin/bash
# SL
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
# ==========================================
# Getting
MYIP=$(wget -qO- ipinfo.io/ip);
echo "Checking VPS"
IZIN=$( curl ipinfo.io/ip | grep $MYIP )
if [ $MYIP = $MYIP ]; then
echo -e "${NC}${GREEN}Permission Accepted...${NC}"
else
echo -e "${NC}${RED}Permission Denied!${NC}";
echo -e "${NC}${LIGHT}Fuck You!!"
exit 0
fi
clear

if [[ "$IP" = "" ]]; then
domain=$(cat /etc/xray/domain)
else
domain=$IP
fi

until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[0;41;36m           XRAY ALL ACCOUNT          \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

		read -rp "User: " -e user
		user_EXISTS=$(grep -w $user /usr/local/etc/xray/config.json | wc -l)

		if [[ ${user_EXISTS} == '1' ]]; then
clear
		echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
		echo -e "\E[0;41;36m           XRAY ALL ACCOUNT          \E[0m"
		echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
			echo ""
			echo "A client with the specified name was already created, please choose another name."
			echo ""
			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
			read -n 1 -s -r -p "Press any key to back on menu"
			xmenu
		fi
	done
#
#
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a\### '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /usr/local/etc/xray/config.json
sed -i '/#trojangrpc$/a\### '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /usr/local/etc/xray/config.json

sed -i '/#vless$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /usr/local/etc/xray/config.json
# sed -i '/#vlessgrpc$/a\### '"$user $exp"'\
# },{"id": "'""$uuid""'","email": "'""$user""'"' /usr/local/etc/xray/config.json

sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /usr/local/etc/xray/config.json
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /usr/local/etc/xray/config.json

#buatvmess
VMESSWS_JSON=$(jq -n \
    --arg uuid "$uuid" \
    --arg email "$user" \
    --arg expiry "$exp" \
    --arg server "$domain" \
    '{
      "v": "2",
      "ps": $email,
      "add": $server,
      "port": 80,
      "id": $uuid,
      "aid": 0,
      "net": "ws",
      "type": "none",
      "host": $server,
      "path": "/vmessws",
      "tls": "false",
      "expiry": $expiry
    }')

VMESSGRPC_JSON=$(jq -n \
    --arg uuid "$uuid" \
    --arg email "$user" \
    --arg expiry "$exp" \
    --arg server "$domain" \
    '{
      "v": "2",
      "ps": $email,
      "add": $server,
      "port": 443,
      "id": $uuid,
      "aid": 0,
      "net": "grpc",
      "type": "none",
      "host": "",
      "path": "vmessgrpc", # Ganti dengan nama service gRPC Anda
      "tls": "tls",
      "expiry": $expiry
    }')

#
VMESSWS_B64=$(echo -n $VMESSWS_JSON | base64 -w 0)
VMESSGRPC_B64=$(echo -n $VMESSGRPC_JSON | base64 -w 0)

systemctl restart xray

#buatvless
vlesslinkws="vless://${uuid}@${domain}:443?path=/xrayws&security=tls&encryption=none&type=ws#${user}"
vlesslinknon="vless://${uuid}@${domain}:80?path=/xrayws&encryption=none&type=ws#${user}"
# vlesslinkgrpc="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=bug.com#${user}"

#buattrojan
trojanlinkgrpc="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojangrpc&sni=${domain}#${user}"
trojanlinkws="trojan://${uuid}@${domain}:443?path=/xraytrojanws&security=tls&host=${domain}type=ws&sni=${domain}#${user}"

#buatshadowsocks
# cipher="aes-128-gcm"
# sed -i '/#ssws$/a\### '"$user $exp"'\
# },{"password": "'""$uuid""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json
# sed -i '/#ssgrpc$/a\### '"$user $exp"'\
# },{"password": "'""$uuid""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json
# echo $cipher:$uuid > /tmp/log
# shadowsocks_base64=$(cat /tmp/log)
# echo -n "${shadowsocks_base64}" | base64 > /tmp/log1
# shadowsocks_base64e=$(cat /tmp/log1)
# shadowsockslink="ss://${shadowsocks_base64e}@$domain:$tls?plugin=xray-plugin;mux=0;path=/xrayssws;host=$domain;tls#${user}"
# shadowsockslink1="ss://${shadowsocks_base64e}@$domain:$tls?plugin=xray-plugin;mux=0;serviceName=ss-grpc;host=$domain;tls#${user}"

systemctl restart xray
# rm -rf /tmp/log
# rm -rf /tmp/log1

# cat > /home/vps/public_html/ss-ws-$user.txt <<-END
# { 
#  "dns": {
#     "servers": [
#       "8.8.8.8",
#       "8.8.4.4"
#     ]
#   },
#  "inbounds": [
#    {
#       "port": 10808,
#       "protocol": "socks",
#       "settings": {
#         "auth": "noauth",
#         "udp": true,
#         "userLevel": 8
#       },
#       "sniffing": {
#         "destOverride": [
#           "http",
#           "tls"
#         ],
#         "enabled": true
#       },
#       "tag": "socks"
#     },
#     {
#       "port": 10809,
#       "protocol": "http",
#       "settings": {
#         "userLevel": 8
#       },
#       "tag": "http"
#     }
#   ],
#   "log": {
#     "loglevel": "none"
#   },
#   "outbounds": [
#     {
#       "mux": {
#         "enabled": true
#       },
#       "protocol": "shadowsocks",
#       "settings": {
#         "servers": [
#           {
#             "address": "$domain",
#             "level": 8,
#             "method": "$cipher",
#             "password": "$uuid",
#             "port": 443
#           }
#         ]
#       },
#       "streamSettings": {
#         "network": "ws",
#         "security": "tls",
#         "tlsSettings": {
#           "allowInsecure": true,
#           "serverName": "isi_bug_disini"
#         },
#         "wsSettings": {
#           "headers": {
#             "Host": "$domain"
#           },
#           "path": "/xrayssws"
#         }
#       },
#       "tag": "proxy"
#     },
#     {
#       "protocol": "freedom",
#       "settings": {},
#       "tag": "direct"
#     },
#     {
#       "protocol": "blackhole",
#       "settings": {
#         "response": {
#           "type": "http"
#         }
#       },
#       "tag": "block"
#     }
#   ],
#   "policy": {
#     "levels": {
#       "8": {
#         "connIdle": 300,
#         "downlinkOnly": 1,
#         "handshake": 4,
#         "uplinkOnly": 1
#       }
#     },
#     "system": {
#       "statsOutboundUplink": true,
#       "statsOutboundDownlink": true
#     }
#   },
#   "routing": {
#     "domainStrategy": "Asls",
# "rules": []
#   },
#   "stats": {}
# }
# END
# cat > /home/vps/public_html/ss-grpc-$user.txt <<-END
# {
#     "dns": {
#     "servers": [
#       "8.8.8.8",
#       "8.8.4.4"
#     ]
#   },
#  "inbounds": [
#    {
#       "port": 10808,
#       "protocol": "socks",
#       "settings": {
#         "auth": "noauth",
#         "udp": true,
#         "userLevel": 8
#       },
#       "sniffing": {
#         "destOverride": [
#           "http",
#           "tls"
#         ],
#         "enabled": true
#       },
#       "tag": "socks"
#     },
#     {
#       "port": 10809,
#       "protocol": "http",
#       "settings": {
#         "userLevel": 8
#       },
#       "tag": "http"
#     }
#   ],
#   "log": {
#     "loglevel": "none"
#   },
#   "outbounds": [
#     {
#       "mux": {
#         "enabled": true
#       },
#       "protocol": "shadowsocks",
#       "settings": {
#         "servers": [
#           {
#             "address": "$domain",
#             "level": 8,
#             "method": "$cipher",
#             "password": "$uuid",
#             "port": 443
#           }
#         ]
#       },
#       "streamSettings": {
#         "grpcSettings": {
#           "multiMode": true,
#           "serviceName": "ss-grpc"
#         },
#         "network": "grpc",
#         "security": "tls",
#         "tlsSettings": {
#           "allowInsecure": true,
#           "serverName": "isi_bug_disini"
#         }
#       },
#       "tag": "proxy"
#     },
#     {
#       "protocol": "freedom",
#       "settings": {},
#       "tag": "direct"
#     },
#     {
#       "protocol": "blackhole",
#       "settings": {
#         "response": {
#           "type": "http"
#         }
#       },
#       "tag": "block"
#     }
#   ],
#   "policy": {
#     "levels": {
#       "8": {
#         "connIdle": 300,
#         "downlinkOnly": 1,
#         "handshake": 4,
#         "uplinkOnly": 1
#       }
#     },
#     "system": {
#       "statsOutboundUplink": true,
#       "statsOutboundDownlink": true
#     }
#   },
#   "routing": {
#     "domainStrategy": "Asls",
# "rules": []
#   },
#   "stats": {}
# }
# END

clear
echo -e "──────✦Xray-Mod✦─────" | tee -a /etc/log-create-user.log
echo -e "INFORMASI AKUN VPN XRAY" | tee -a /etc/log-create-user.log
echo -e "IP         : $MYIP" | tee -a /etc/log-create-user.log
echo -e "Host/Domain: $domain" | tee -a /etc/log-create-user.log
echo -e "Password/ID: $uuid" | tee -a /etc/log-create-user.log
echo -e "────────✦Port✦───────" | tee -a /etc/log-create-user.log
#echo -e "Ws TLS : 443" | tee -a /etc/log-create-user.log
echo -e "Ws NTLS: 80" | tee -a /etc/log-create-user.log
echo -e "GRPC   : 443" | tee -a /etc/log-create-user.log
#echo -e "*Note OPOK: opok only supports coremeta"
#echo -e "*Note SHADOWSOCKS: gunakan custom config atau plugin xray"
#echo -e "──────────✦✦─────────" | tee -a /etc/log-create-user.log
#echo -e "" | tee -a /etc/log-create-user.log
#echo -e "────✦Path Trojan✦────" | tee -a /etc/log-create-user.log
#echo -e "=>WS TLS: /xraytrojanws" | tee -a /etc/log-create-user.log
#echo -e "=>GRPC  : trojan-grpc" | tee -a /etc/log-create-user.log
#echo -e "=>OPOK  : ws://bugcom/xraytrojanws" | tee -a /etc/log-create-user.log
#echo -e "──────────✦✦─────────" | tee -a /etc/log-create-user.log
#echo -e "🔹Config-Trojan-WS-TLS🔹" | tee -a /etc/log-create-user.log
#echo -e "$trojanlinkws" | tee -a /etc/log-create-user.log
#echo -e "" | tee -a /etc/log-create-user.log
echo -e "🔹Config-Trojan-WS-GRPC🔹" | tee -a /etc/log-create-user.log
echo -e "$trojanlinkgrpc" | tee -a /etc/log-create-user.log
echo -e "" | tee -a /etc/log-create-user.log

# echo -e "Protokol VPN: SHADOWSOCKS" | tee -a /etc/log-create-user.log
# echo -e "Network: WS/GRPC" | tee -a /etc/log-create-user.log
# echo -e "Method Cipers : aes-128-gcm" | tee -a /etc/log-create-user.log
# echo -e "====== Path =======" | tee -a /etc/log-create-user.log
# echo -e "=>WS TLS: /xrayssws" | tee -a /etc/log-create-user.log
# echo -e "=>GRPC  : ss-grpc" | tee -a /etc/log-create-user.log
# echo -e "=>OPOK  : ws://bugcom/xrayssws" | tee -a /etc/log-create-user.log
# echo -e "====== SHADOWSOCKS WS TLS=======" | tee -a /etc/log-create-user.log
# echo -e "URL Custom Config WS TLS   :http://${domain}:89/ss-ws-$user.txt" | tee -a /etc/log-create-user.log
# echo -e "====== SHADOWSOCKS GRPC TLS=======" | tee -a /etc/log-create-user.log
# echo -e "URL Custom Config GRPC TLS : http://${domain}:89/ss-grpc-$user.txt" | tee -a /etc/log-create-user.log
# echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | tee -a /etc/log-create-user.log
# echo -e "" | tee -a /etc/log-create-user.log
# echo -e "─────✦Path Vless✦────" | tee -a /etc/log-create-user.log
# echo -e "=>WS TLS: /xrayws" | tee -a /etc/log-create-user.log
# echo -e "=>GRPC  : vless-grpc" | tee -a /etc/log-create-user.log
# echo -e "=>OPOK  : ws://bugcom/xrayws" | tee -a /etc/log-create-user.log
# echo -e "──────────✦✦─────────" | tee -a /etc/log-create-user.log
# echo -e "🔹Config-Vless-WS-NTLS🔹" | tee -a /etc/log-create-user.log
# echo -e "$vlesslinknon" | tee -a /etc/log-create-user.log
# echo -e "" | tee -a /etc/log-create-user.log
# echo -e "🔹Config-Vless-WS-TLS🔹" | tee -a /etc/log-create-user.log
# echo -e "$vlesslinkws" | tee -a /etc/log-create-user.log
# echo -e "=============================" | tee -a /etc/log-create-user.log
# echo -e "====== Vless GRPC TLS =======" | tee -a /etc/log-create-user.log
# echo -e "$vlesslinkgrpc" | tee -a /etc/log-create-user.log
# echo -e "=============================" | tee -a /etc/log-create-user.log
# echo -e "" | tee -a /etc/log-create-user.log
echo -e "" | tee -a /etc/log-create-user.log
#echo -e "─────✦Path Vmess✦────" | tee -a /etc/log-create-user.log
#echo -e "=> WS TLS : /xrayvws" | tee -a /etc/log-create-user.log
#echo -e "=> GRPC   : vmess-grpc" | tee -a /etc/log-create-user.log
#echo -e "=> OPOK   : ws://bugcom/xrayvws" | tee -a /etc/log-create-user.log
echo -e "─────────✦✦──────────" | tee -a /etc/log-create-user.log
echo -e "🔹Config-Vmess-WS-NTLS🔹" | tee -a /etc/log-create-user.log
echo -e "vmess://$VMESSWS_B64" | tee -a /etc/log-create-user.log
echo -e "" | tee -a /etc/log-create-user.log
#echo -e "🔹Config-Vmess-WS-GRPC🔹" | tee -a /etc/log-create-user.log
#echo -e "vmess://$VMESSGRPC_B64" | tee -a /etc/log-create-user.log

#echo "" | tee -a /etc/log-create-user.log
cd
