#!/bin/bash
clear
echo -e "\e[36m╒════════════════════════════════════════════════════╕\033[0m"
echo -e " \E[0;41;36m                     INFO SERVER                    \E[0m"
echo -e "\e[36m╘════════════════════════════════════════════════════╛\033[0m"

uphours=`uptime -p | awk '{print $2,$3}' | cut -d , -f1`
upminutes=`uptime -p | awk '{print $4,$5}' | cut -d , -f1`
uptimecek=`uptime -p | awk '{print $6,$7}' | cut -d , -f1`
cekup=`uptime -p | grep -ow "day"`
IPVPS=$(curl -s ipinfo.io/ip )
ISPVPS=$( curl -s ipinfo.io/org )
#clear
if [ "$cekup" = "day" ]; then
echo -e "System Uptime   :  $uphours $upminutes $uptimecek"
else
echo -e "System Uptime   :  $uphours $upminutes"
fi
echo -e "IP-VPS          :  $IPVPS"
echo -e "ISP-VPS         :  $ISPVPS"
echo "╔════════════════════════════════════════════════════╗"
echo -e " \E[0;41;36m               🔹 Script By Yon-Mod 🔹              \E[0m"
echo "╚════════════════════════════════════════════════════╝"
echo "╔════════════════════════════════════════════════════╗"
echo -e " \E[0;44;33m Link Script➤https://github.com/reokadhafi/myxray \E[0m"
echo "╚════════════════════════════════════════════════════╝"
echo "╔════════════════════════════════════════════════════╗"
echo -e " \E[0;41;36m                  🔹 XRAY XMENU 🔹                  \E[0m"
echo "╚════════════════════════════════════════════════════╝"
echo "║1 ║ Create Account                                  ║"
echo "║2 ║ Delete Account                                  ║"
echo "║3 ║ Domain Name Checker                             ║"
echo "║4 ║ Check Public IP                                 ║"
echo "║5 ║ Update Script                                   ║"
echo "║6 ║ Restart Service XRAY                            ║"
echo "║7 ║ Speedtest Server                                ║"
echo "║8 ║ Reboot VPS                                      ║"
echo "║0 ║ Exit Menu                                       ║"
echo "╚════════════════════════════════════════════════════╝" 
read -p "╰┈➤Select From Options [1-69 or x] :  " xmenu
case $xmenu in 
1)
./add_akun
;;
2)
./delete_akun
;;
3)
cat /etc/xray/domain
;;
4)
curl -s ipinfo.io/ip
;;
5)
./updatedll
;;
6)
./restart_xray
;;
7)
speedtest
;;
8)
reboot
;;
0)
exit
;;
*)
echo "Input The Correct Number !"
;;
esac
